name: Deploy Bot to Hetzner

on:
  push:
    branches: [ main ]  # Проверь, как называется твоя ветка: main или master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/ai_bot
            # Инициализируем гит, если его нет
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/${{ github.repository }}
            fi
            # Принудительно забираем код, игнорируя то, что папка не пуста
            git fetch --all
            git reset --hard origin/main
            # Запускаем магию Docker
            docker compose up --build -d